In [212]:
import pandas as pd
df=pd.read_csv('./표준화완성본.csv')
df

credit_score  balance_per_age  balance_per_tenure  salary_per_products  \
0        -0.326221        -0.402237            0.439067             0.511633   
1        -0.440036        -1.141788            0.517514             0.726664   
2        -1.536794         0.464244           -0.450913            -0.705735   
3         0.501521        -0.201650            1.239547            -0.534073   
4         2.063884        -0.342349            0.514829             0.083927   
...            ...              ...                 ...                  ...   
9995      1.246488        -0.201650           -0.361412            -0.510598   
9996     -1.391939        -1.511880           -0.952871             0.518374   
9997      0.604988         0.032368           -0.561532            -0.626813   
9998      1.256835        -1.376280           -0.409684            -0.543083   
9999      1.463771         1.237862           -0.118732            -0.701632   

      active_member  churn  country_France  country_Germany  country_Spain  \
0               1.0    1.0             1.0              0.0            0.0   
1               1.0    0.0             0.0              0.0            1.0   
2               0.0    1.0             1.0              0.0            0.0   
3               0.0    0.0             1.0              0.0            0.0   
4               1.0    0.0             0.0              0.0            1.0   
...             ...    ...             ...              ...            ...   
9995            0.0    0.0             1.0              0.0            0.0   
9996            1.0    0.0             1.0              0.0            0.0   
9997            1.0    1.0             1.0              0.0            0.0   
9998            0.0    1.0             0.0              1.0            0.0   
9999            0.0    0.0             1.0              0.0            0.0   

      age_group_gender_eighties_Female  ...  \
0                                  0.0  ...   
1                                  0.0  ...   
2                                  0.0  ...   
3                                  0.0  ...   
4                                  0.0  ...   
...                                ...  ...   
9995                               0.0  ...   
9996                               0.0  ...   
9997                               0.0  ...   
9998                               0.0  ...   
9999                               0.0  ...   

      age_group_gender_seventies_Female  age_group_gender_seventies_Male  \
0                                   0.0                              0.0   
1                                   0.0                              0.0   
2                                   0.0                              0.0   
3                                   0.0                              0.0   
4                                   0.0                              0.0   
...                                 ...                              ...   
9995                                0.0                              0.0   
9996                                0.0                              0.0   
9997                                0.0                              0.0   
9998                                0.0                              0.0   
9999                                0.0                              0.0   

      age_group_gender_sixties_Female  age_group_gender_sixties_Male  \
0                                 0.0                            0.0   
1                                 0.0                            0.0   
2                                 0.0                            0.0   
3                                 0.0                            0.0   
4                                 0.0                            0.0   
...                               ...                            ...   
9995                              0.0                            0.0   
9996                              0.0                 

In [213]:
# 표준화된 데이터 말고 주성분 분석을 했다
# 주성분 데이터프레임으로 모델 학습을 시도한다

# 주성분 데이터프레임-표준화, 원핫인코딩, 종속 변수 제외

In [214]:
df2 = df[df.columns.difference(['churn'])]

# pca

In [215]:
import pandas as pd
from sklearn.decomposition import PCA

n=6
li=[]
for i in range(1,n+1):
    prin=f'principal {i}'
    li.append(prin)

# 2. PCA 적용
pca = PCA(n_components=n)  # 주성분의 개수 설정
principal_components = pca.fit_transform(df2)

# 결과를 데이터프레임으로 변환
pca_df = pd.DataFrame(data=principal_components, columns=li)

In [216]:
pca_df

principal 1  principal 2  principal 3  principal 4  principal 5  \
0       -0.081152     0.714698     0.111165     0.511516     0.620504   
1       -0.612193     1.034555     0.228446     0.993473    -0.566902   
2       -0.001868     0.225956    -1.739145    -0.414447     0.543115   
3        0.708717    -0.490695     0.242860     1.120250     0.624937   
4        0.058692    -0.990903     1.844525     0.639159    -0.581803   
...           ...          ...          ...          ...          ...   
9995    -0.300257    -1.169865     0.694020    -0.093036     0.626421   
9996    -1.760475     1.175212    -0.819321     0.081631     0.675815   
9997    -0.287707    -0.960169     0.081031    -0.292959     0.620921   
9998    -1.328276    -1.046260     0.837419     0.730312    -0.581993   
9999     0.971909    -1.543868     0.652107    -0.782628     0.554045   

      principal 6  
0        0.250174  
1        0.786106  
2       -0.440954  
3       -0.463350  
4        0.739728  
...           ...  
9995    -0.238671  
9996     0.500717  
9997     0.218612  
9998    -0.908688  
9999    -0.410409  

[10000 rows x 6 columns]

In [217]:
pca.explained_variance_ratio_.cumsum()

array([0.19967529, 0.37673071, 0.55023557, 0.70588981, 0.77126845,
       0.81608634])

In [218]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline
warnings.filterwarnings('ignore')

In [219]:
x = pca_df
y = df['churn']

In [220]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.2)

# random forest

In [221]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(random_state=42)
classifier.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [222]:
y_pred = classifier.predict(x_test)
print("Accuracy:",accuracy_score(y_test,y_pred)*100)

Accuracy: 82.39999999999999


# xgboost

In [223]:
xgb=XGBClassifier(random_state=42)

In [224]:
xgb.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

In [225]:
xgb_y_pred=xgb.predict(x_test)

In [226]:
print("Accuracy:",accuracy_score(y_test,y_pred)*100)

Accuracy: 82.39999999999999


# decision tree

In [227]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 모델 초기화
clf = DecisionTreeClassifier(random_state=42)

# 모델 학습
clf.fit(x_train, y_train)

# 예측
y_pred = clf.predict(x_test)

# 평가
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# 분류 보고서
print("Classification Report:")
print(classification_report(y_test, y_pred))

# 혼동 행렬
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7445
Classification Report:
              precision    recall  f1-score   support

         0.0       0.84      0.85      0.84      1607
         1.0       0.34      0.33      0.34       393

    accuracy                           0.74      2000
   macro avg       0.59      0.59      0.59      2000
weighted avg       0.74      0.74      0.74      2000

Confusion Matrix:
[[1358  249]
 [ 262  131]]


# logistic regression

In [228]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 로지스틱 회귀 모델 초기화
model = LogisticRegression(
    # solver='liblinear',
    random_state=42)

# 모델 학습
model.fit(x_train, y_train)

# 예측
y_pred = model.predict(x_test)

# 평가
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# 분류 보고서
print("Classification Report:")
print(classification_report(y_test, y_pred))

# 혼동 행렬
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8150
Classification Report:
              precision    recall  f1-score   support

         0.0       0.83      0.97      0.89      1607
         1.0       0.60      0.17      0.27       393

    accuracy                           0.81      2000
   macro avg       0.72      0.57      0.58      2000
weighted avg       0.78      0.81      0.77      2000

Confusion Matrix:
[[1563   44]
 [ 326   67]]


# 

In [229]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# SVM 모델 초기화
model = SVC(random_state=42)

# 모델 학습
model.fit(x_train, y_train)

# 예측
y_pred = model.predict(x_test)

# 평가
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# 분류 보고서
print("Classification Report:")
print(classification_report(y_test, y_pred))

# 혼동 행렬
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8095
Classification Report:
              precision    recall  f1-score   support

         0.0       0.81      0.99      0.89      1607
         1.0       0.63      0.07      0.13       393

    accuracy                           0.81      2000
   macro avg       0.72      0.53      0.51      2000
weighted avg       0.78      0.81      0.74      2000

Confusion Matrix:
[[1590   17]
 [ 364   29]]
